#index:
#    path: /
#    controller: App\Controller\DefaultController::index
job:
  type: rest
  resource: App\Controller\JobController
category:
  type: rest
  resource: App\Controller\CategoryController
zipcode:
  type: rest
  resource: App\Controller\ZipcodeController
app.swagger_ui:
  path: /doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
